### ISSUE TITLE
Hygiene Checklist / Roadmap 

### ISSUE THREAD

**Issue by SamiTriki** [Financial-Times/o-ads#187]
## Hygiene Roadmap
This is used to track the global picture of where we want to make it easier to work with the library for developers and users.

Feel free to amend / edit directly and comment, add your own issues.

Checked when the change has been released

#### Release process 
At the moment, the release process is manual, many mistakes can occur, like forgetting to bump up a version number
- [ ] Comprehensive versionning and deploy steps documentation

#### Development
One issue that adds quite a lot of friction with development is how non straightforward it is to just make changes locally and test them within other sites
 - [ ] Rewrite dev steps with case to test the library in isolation or within n-ui. 
 - [ ] Easy copy/paste steps to get started with the library and coding right away
 
#### Library
- [ ] Remove FT  Specific pieces of logic / doc and move them to ft.com
- [ ] Remove deprecated code
- [ ] Process for deprecation
- [ ] Examine old todos, check relevance

### Documentation
- [ ] Easier get started guide, copy/paste style with minimum config to run ads
- [ ] Deeper documentation for every config option, alphabetically ordered list of method/functions/properties that lead to a deeper explanation

### Quality
- [ ] Check old github issue for relevance
- [ ] Big linting run on the codebase to get rid of errors and not commit them moving forward
- [ ] Concistency run on the codebase, on attribute parser, library initialisation. there's too many ways to do the same thing 
- [ ] Add developer warnings for known missuses of the library

**Comment by alexflorisca** [comment]
Closing this as we are not actively developing o-ads anymore
